# Generated by Django 5.0.3 on 2024-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_purchase_amount_cart_product_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
